frontend:

homeassistant:
  latitude: 48
  longitude: 11
  elevation: 519
  name: Home
  temperature_unit: C
  time_zone: Europe/Berlin
  unit_system: metric

map:
history:
config:

# cloud:
#   alexa:

discovery:

# ifttt:
#   key: ifttt_key

sun:
# Weather prediction
sensor:
  - platform: yr

hue:
  bridges:
    - host: 192.168.178.20
      allow_unreachable: true

switch:
  - platform: tplink
    host: 192.168.178.24

device_tracker:
  - platform: fritz
# alexa:
