# Default values for homeassistant.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

## Add image for HA dashboard

replicaCount: 1

image:
  repository: homeassistant/home-assistant
  tag: 0.62.1
  pullPolicy: Always
  containerport: 8123

configFiles:
  configuration: "https://raw.githubusercontent.com/swibrow/kube-charts/master/homeassistant/configuration.yml"
  phue: "https://raw.githubusercontent.com/swibrow/kube-charts/master/homeassistant/phue.conf"

service:
  # name: homeassistant
  type: ClusterIP
  port: 80
  targetport: 8123

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik
    # kubernetes.io/tls-acme: "true"
  hosts:
    - homeassistant.k8s.wibrow.net
  # tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
